// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class TClientesTipo
{
    public int ClienteTipoId { get; set; }

    public string ClienteTipoNombre { get; set; }

    public string ClienteTipoDescrip { get; set; }

    public virtual ICollection<TClientes> TClientes { get; set; } = new List<TClientes>();
}