// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class TClientes
{
    public int ClienteId { get; set; }

    public int? ClienteTipoId { get; set; }

    public string ClienteNombre { get; set; }

    public string ClienteApellido { get; set; }

    public string ClienteCedula { get; set; }

    public DateOnly ClienteFechaNac { get; set; }

    public string ClienteEmail { get; set; }

    public string ClienteTelf { get; set; }

    public virtual TClientesTipo ClienteTipo { get; set; }
}