// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class TCompras
{
    public int CompraId { get; set; }

    public int? PuntoVentaId { get; set; }

    public int? ClienteId { get; set; }

    public string CompraCodigoUnico { get; set; }

    public int ProductoCompradoCantidad { get; set; }

    public decimal ProductoCompradoPrecio { get; set; }

    public virtual TPuntosVenta PuntoVenta { get; set; }
}