// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class TProductosCentrosDistribucion
{
    public int? ProductoId { get; set; }

    public int? CentroDistribucionId { get; set; }

    public int? ProductoCantidadUnidades { get; set; }

    public virtual TCentrosDistribucion CentroDistribucion { get; set; }

    public virtual TProductos Producto { get; set; }
}