// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class TProductos
{
    public int ProductoId { get; set; }

    public string ProductoNombre { get; set; }

    public decimal ProductoPrecioMayorista { get; set; }

    public decimal ProductoPrecioMinorista { get; set; }

    public string ProductoDescrip { get; set; }

    public virtual ICollection<TPedidos> TPedidos { get; set; } = new List<TPedidos>();
}