// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class TPuntosVenta
{
    public int PuntoVentaId { get; set; }

    public string PuntoVentaCiudad { get; set; }

    public string PuntoVentaDireccion { get; set; }

    public virtual ICollection<TCompras> TCompras { get; set; } = new List<TCompras>();

    public virtual ICollection<TPedidos> TPedidos { get; set; } = new List<TPedidos>();
}